<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>WhatDidIDo</AssemblyName>
    <RootNamespace>WhatDidIDo</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>WhatDidIDo.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="WhatDidIDo.ico" />
  </ItemGroup>

</Project>
